inipreload {
    path = /home/quinn/Pictures/gruvbox-penguin-wallpaper.jpg
}

wallpaper {
    monitor = DP-1
    path = /home/quinn/Pictures/gruvbox-penguin-wallpaper.jpg
}

wallpaper {
    monitor = DP-2
    path = /home/quinn/Pictures/gruvbox-penguin-wallpaper.jpg
}

splash = false
